/*
 * Authentication actions types
 */
export const SET_USERNAME  = 'SET_USERNAME';
export const SET_PASSWORD  = 'SET_PASSWORD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR   = 'LOGIN_ERROR';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_RETRY   = 'LOGIN_RETRY';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';

export const FETCH_EXAMINATION_TRAININGS_SUCCESS = 'FETCH_EXAMINATION_TRAININGS_SUCCESS';
export const FETCH_PEDAGOGICAL_TRAININGS_SUCCESS = 'FETCH_PEDAGOGICAL_TRAININGS_SUCCESS';
export const FETCH_THEMATICAL_TRAININGS_SUCCESS  = 'FETCH_THEMATICAL_TRAININGS_SUCCESS';
